### ISSUE TITLE
Purpose of Discord.register?

### ISSUE THREAD

**Issue by ScottyFillups** [discordjs/RPC#103]
What's the purpose of this function? https://github.com/discordjs/RPC/blob/master/src/util.js#L6

I don't see why you'd want to register your client ID as a protocol: when would you want to invoke your electron application using `clientID://` as the protocol?

**Comment by devsnek** [comment]
That functionality had to do with game store and library registration. I don't believe it is used anymore.

**Comment by ScottyFillups** [comment]
Thanks the quick reply!
