### ISSUE TITLE
Rich presence only shows on client's machine

### ISSUE THREAD

**Issue by r0hin** [discordjs/RPC#106]
I've got an electron app that shows something like this:
```
rpc.setActivity({
  details: 'Idling',
  state: 'Waiting',
  startTimestamp,
  largeImageKey: 'snek_large',
  largeImageText: 'Image',
  instance: false,
  startTimestamp: Math.round(Date.now() / 1000),
});
```
The rich presence is only shown on my own computer and when looking at my profile from other devices or instances, it's not shown. Any help with this is appreciated! Thanks!

**Comment by devsnek** [comment]
That is expected.
