### ISSUE TITLE
Include Functionality to Change Activity Type

### ISSUE THREAD

**Issue by fiercedeity-productions** [discordjs/RPC#116]
According to the [Discord Developer Portal](https://discord.com/developers/docs/game-sdk/activities), it is possible to change the default message of "Playing" (game) to "Listening", "Streaming" or a custom string, but having looked over the documentary to the discordjs RPC, it seems as if this has not been ported over yet.

Could this feature be included in a future release? If not, are there any workarounds for changing the message manually?

![image](https://user-images.githubusercontent.com/31538456/109402161-76f1d380-794b-11eb-99f5-2d7ad2834497.png)

**Comment by advaith1** [comment]
only bots and certain private integrations can set that, it cannot be publicly set via ipc

**Comment by fiercedeity-productions** [comment]
Ah I see. That's a shame. Hopefully Discord will be more open and flexible about this in the future.

**Comment by richiedevs** [comment]
Hopefully.
