### ISSUE TITLE
Buttons are not working

### ISSUE THREAD

**Issue by YodaLightsabr** [discordjs/RPC#123]
![image](https://user-images.githubusercontent.com/76178582/110680802-ebb7df80-818d-11eb-90f8-bba1e1cb010a.png)
What am I supposed to pass to the object? I have tried many different configurations, but there's no documentation about it and I keep getting errors.

**Comment by vBread** [comment]
It's the same as [ActivityOptions](https://discord.js.org/#/docs/main/stable/typedef/ActivityOptions).

**Comment by YodaLightsabr** [comment]
> It's the same as [ActivityOptions](https://discord.js.org/#/docs/main/stable/typedef/ActivityOptions).

Are you sure? Because bot presences and user presences are different.

**Comment by YodaLightsabr** [comment]
```
    {
        "startTimestamp": "Date.now()",
        "details": "Google",
        "buttons": [
            { "label": "Google1", "url": "https://google.com" },
            { "label": "Google2", "url": "https://google.com" }
        ]
    }
```
that's the object I'm passing, but the buttons are not working.

**Comment by advaith1** [comment]
1. what version are you on?
2. wdym "not working"?

**Comment by NotSugden** [comment]
#91 does add documentation for this

**Comment by YodaLightsabr** [comment]
> 1. what version are you on?
> 2. wdym "not working"?

1. Previously 3.1.4, but I updated and it still didn't work
2. Everything works except for the buttons. Also, the object I'm passing is essnetially read from a JSON file and it replaces "Date.now()" as a string with the time that the status is set so that the time can be from when I start my program.
![image](https://user-images.githubusercontent.com/76178582/110879558-0b383080-8292-11eb-8401-3187ffd18784.png)
That's a picture of what the status looks like, where the buttons should be working, but they aren't.

**Comment by YodaLightsabr** [comment]
> #91 does add documentation for this

Ok, so after looking at that, my `buttons` property is an array of two button objects. They look like:
```json
{ "label": "Visit Google", "url": "https://google.com" }
```
just like it is supposed to, but it's not working. The buttons aren't being displayed.

**Comment by ChingChang9** [comment]
I am on 3.2.0 and it works for me. The arguments you pass in look right, so my guess is this:
You said you are reading from a JSON file and replacing certain fields. Are you parsing the JSON file correctly? Maybe try to `console.log` the json data and use `typeof` to check the data type of each field in the json. Make sure they are an array of objects, not a string

**Comment by YodaLightsabr** [comment]
Okay I'll show you what the console.log'd data looks like

**Comment by YodaLightsabr** [comment]
![image](https://user-images.githubusercontent.com/76178582/111011217-890d4200-834d-11eb-90c9-db41bfb8e7bd.png)

**Comment by YodaLightsabr** [comment]
@ChingChang9 There you go ^

**Comment by advaith1** [comment]
Have you tried fully uninstalling and reinstalling `discord-rpc`? it may not have updated properly

**Comment by ChingChang9** [comment]
Hm yeah it seems to be in the proper format. Check the your `node_modules/discord-rpc/src/client.js`. It should have `buttons: args.buttons,` on line 537 if you're on 3.2.0. Otherwise, you might have not updated the package properly.

**Comment by YodaLightsabr** [comment]
Good idea. Give me a minute.

**Comment by YodaLightsabr** [comment]
Welp. Apparently my package.json got moved to the parent directory somehow, and when I ran npm install it said 

removed 3 packages in 0.622s

so I fixed that and now it's working. Sorry for bugging the issue section about my stupid mistake.
