### ISSUE TITLE
Cannot download discord-rpc with npm

### ISSUE THREAD

**Issue by donaldtrumpyyy** [discordjs/RPC#129]
Hello everyone,

Currently, when I'm executing `npm i discord-rpc@latest` command, I've a crash log with Python and some other items 😬
Here's the crash log : https://code.alwyn974.re/onosafowad.sql

Do you have an idea about why can't I download the last version ?

Really thanks for your help and have a nice day,
Corentin

**Comment by vaporox** [comment]
If you only need rich presence, install with `--legacy-peer-deps`

**Comment by donaldtrumpyyy** [comment]
Thanks for the help @vaporox it works with that ❤️
