### ISSUE TITLE
Vulnerability issue with ws

### ISSUE THREAD

**Issue by ChingChang9** [discordjs/RPC#138]
Hi I'm new to open source so sorry if this is idiodic, but I've been getting security alerts from github's dependabot saying that there is a vulnerbility issue with ws with version <= 7.4.6. I'm wondering if we should upgrade the version of ws in `package.json`. I made a pull request that fixes this: #139

For more information, this is what the full security alert says:
![image](https://user-images.githubusercontent.com/38874004/120350837-5419e700-c2cd-11eb-89c3-25f588709c25.jpeg)

Thanks!

**Comment by devsnek** [comment]
This package does not operate a websocket server and is therefore unaffected.
