### ISSUE TITLE
Documentation link in README broken

### ISSUE THREAD

**Issue by IceTank** [discordjs/RPC#141]
The current link (https://discord.js.org/#/docs/rpc/) leads to a broken page.

**Comment by alanbixby** [comment]
Throwing my two cents out there, I cannot replicate this issue and my browser automatically redirects to the URL provided in #142.

---

Are you interpreting sparseness as a broken page? The package one has one class:

![image](https://user-images.githubusercontent.com/34300238/122643680-33c89580-d0df-11eb-9b9c-12f0e27c4891.png)

**Comment by kyranet** [comment]
You have old cache, @alanbixby. Please do Shift + F5 or Ctrl + F5 (check your favourite search engine for "How to hard refresh in [Browser Name]" if those didn't work).

It should look like this:

![image](https://user-images.githubusercontent.com/24852502/122644002-1b726e00-d113-11eb-8dfa-c3d206e79b26.png)

**Comment by alanbixby** [comment]
Yep, you're right. My smoothbrain decided to purge the `discord.com` cache instead of the `discord.js.org` before commenting.

**Comment by zisra** [comment]
Link still seems to be broken?
