### ISSUE TITLE
error: connection closed

### ISSUE THREAD

**Issue by MRVaron** [discordjs/RPC#144]
i cant use discord-rpc module. example doesnt work too(( error: connection closed. ipc and websocket. help me plz

![image](https://user-images.githubusercontent.com/53368344/122671997-fbee4a80-d1d1-11eb-87f4-51388f77c69b.png)

**Comment by thehairy** [comment]
And whats the related code?

Things to consider when getting a connection closed/could not connect error:
• What transport are you using? If it's 'websocket', change that to 'ipc'
• Is the ID you are trying to login with your user ID? If so, get one from the developer portal instead
• Are you using the Discord app? It won't be able to connect to the web version
• Is your code running on the same machine as the Discord app?
• Are you trying to run it from WSL? If so, it won't be able to connect either
• Have you installed Discord from the snap store? If so, install it from your distro's package repository or directly from the Discord website

**Comment by MRVaron** [comment]
> И что за код?
> 
> Что следует учитывать при закрытии соединения / ошибка не удалось подключиться:
> • Какой транспорт вы используете? Если это «websocket», измените его на «ipc»
> • Идентификатор, который вы пытаетесь войти в систему, соответствует вашему идентификатору пользователя? Если да, то получите его на портале разработчика.
> • Вы используете приложение Discord? Он не сможет подключиться к веб-версии.
> • Ваш код работает на том же компьютере, что и приложение Discord?
> • Вы пытаетесь запустить его из WSL? Если да, то он тоже не сможет подключиться
> • Вы установили Discord из магазина оснасток? Если да, установите его из репозитория пакетов вашего дистрибутива или прямо с веб-сайта Discord.

it is example

**Comment by MRVaron** [comment]
i tryed websocket and ipc. my code doesnt work too: 
```js
const clientId = 'xxx';


const RPC = require('discord-rpc');

const client = new RPC.Client({ transport: 'ipc' });

client.on('ready', () => {
  console.log("Ready");

});

// Log in to RPC with client id
client.login(clientId, {clientSecret: "xxx"});```

**Comment by MRVaron** [comment]
> Я пробовал websocket и ipc. мой код тоже не работает:
> 
> ```js
> const  clientId  =  'ххх' ;
> 
> 
> const  RPC  =  require ( 'discord-rpc' ) ;
> 
> const  client  =  новый  RPC . Клиент ( {  транспорт : 'ipc'  } ) ;
> 
> клиент . on ( 'готово' ,  ( )  =>  { 
>   console . log ( "Готово" ) ;
> 
> } ) ;
> 
> // Войдите в RPC с идентификатором 
> клиента client . логин ( clientId ,  { clientSecret : "xxx" } ) ; `` ''
> ```

clientid is id of my application
![image](https://user-images.githubusercontent.com/53368344/122672321-b3379100-d1d3-11eb-9ac2-d72df02adec7.png)

**Comment by MRVaron** [comment]
im sorry. it works! i used client.login(clientId, {clientSecret: "xxx"}). i try use client.login({clientId:client_id}); and it works
