### ISSUE TITLE
Discord RPC via Browser

### ISSUE THREAD

**Issue by RayhanADev** [discordjs/RPC#148]
I see this package is bundled as a UMD module meaning it should be available for use via browser, and your README says the example was made for the browser however I cannot for the life of me figure out why I can't run it.

For context, I get the connect closed error and I'm using Websockets as my transport method. 

Any help would be appreciated, thanks :D.

**Comment by devsnek** [comment]
You need to be whitelisted by discord to use websockets.

**Comment by RayhanADev** [comment]
@devsnek okay thank you :).
