### ISSUE TITLE
Buttons not working properly

### ISSUE THREAD

**Issue by fardeem** [discordjs/RPC#165]
I am setting the activity with:

```
    buttons: [
      {
        label: 'Join',
        url: 'https://discord.com/',
      },
    ],
```

<img width="316" alt="image" src="https://user-images.githubusercontent.com/2018374/154627540-ce07f5df-48aa-43ec-b03f-60d55738162f.png">

The button appears but when you click on it, nothing happens. What can I do to make it work?

**Comment by SupertigerDev** [comment]
Same

**Comment by SHUSTRIK-Milan** [comment]
It doesn't work just for you

**Comment by mertssmnoglu** [comment]
When another person clicked on it, it works. You can't click on your personal button, it's not an issue about the source code.
