### ISSUE TITLE
Buttons not working?

### ISSUE THREAD

**Issue by xCopyCat2** [discordjs/RPC#180]
Ever since the new update I can't seem to use buttons but anything else works... Here is an image.
![image](https://github.com/discordjs/RPC/assets/140447150/bd31b9f8-65a0-437c-8eba-1d2463155f04)

**Comment by pixxies** [comment]
It looks like this is a Discord desktop client issue. I also don't have the buttons when I look on the desktop app (MacOS), but I do see the buttons if I check my profile on the iOS app. Discord are updating profiles with the new compact versions and that's likely messing with / hiding the buttons on purpose to make them more compact.

In short, the package seems to be working as normal, it's just the Discord client that may not render it based on whatever version of the current profile experiment you have.

**Comment by yurixahri** [comment]
I think they stop render your own button since you can't click it, others can still see it.
![image](https://github.com/user-attachments/assets/0c1b8890-2bd6-45a9-a7f2-1722626ece37)
