### ISSUE TITLE
completely broken in firefox 60

### ISSUE THREAD

**Issue by mmis1000** [discordjs/RPC#32]
Does not load at all due to throws 

```
TypeError: can't convert undefined to object
```

inspected with dev tools on a development build found

```
  static mixin(store, ignored) {
    Object.getOwnPropertyNames(Collection.prototype)
      .concat(Object.getOwnPropertyNames(Map.prototype)).forEach(prop => {
```

`Collection` here is not a function

**Comment by devsnek** [comment]
@mmis1000 that's not even in the rpc codebase: https://github.com/discordjs/discord.js/blob/5071477172053ef9d274aaab16cec0cfbd25b860/src/util/Util.js#L406

**Comment by mmis1000** [comment]
If it is caused by wrong discord.js version.
THEN YOU STILL NEED YOU FIX THE PACKAGE.JSON!
Why do you ever want to add github repo to package.json without a commit hash?
Doesn't this mean this package will break at any time when the upsteram repo break?

**Comment by devsnek** [comment]
rpc is still in beta, it's not inherently stable

**Comment by mmis1000** [comment]
At least you should't make it build success or fail randomly.
Use it in this way completely make version control useless
