### ISSUE TITLE
IPC Path Problem On Ubuntu 18.04

### ISSUE THREAD

**Issue by PolyMagic** [discordjs/RPC#36]
### Problem
So... On Ubuntu 18.04 path to discord ipc is ``` /run/user/1000/snap.discord/discord-ipc-{Id} ``` 
instead of ``` /run/user/1000/discord-ipc-{Id} ``` with cause ``` Could not connect ``` error

### WorkAround For Ubuntu Users
Hard code new path to every ``` discord-rpc/src/transports/IPC.js ``` file on your computer.
Path is on line 128.
```js
return `${prefix.replace(/\/$/, '')}/snap.discord/discord-ipc-${id}`;
```

**Comment by devsnek** [comment]
my library matches with discord's reference implementation: https://github.com/discordapp/discord-rpc/blob/7c41a8ec1969b9b4b0c2360c6b632ebd16a92b69/src/connection_unix.cpp#L29

open an issue on that repo if you find the behaviour unsatisfactory.
