### ISSUE TITLE
code: 4000 No Client ID Specified

### ISSUE THREAD

**Issue by SgtBreadStick** [discordjs/RPC#38]
I had to downgrade my discord-rpc version due to this annoying error that does not make sense.
_**"{ code: 4000, message: 'No Client ID Specified' }"**_

The NPM/Node App we have created is having issues because of the new discord-rpc update, its not the only thing that has had an update and is going wrong. We have specified everything and it worked perfectly before, this is the console log

> Rich Presence plugin starting
> Version: 1.0.0
> Platform: win32
> Startup parameters:
> { _: [], help: false, version: false, dev: true, '$0': 'index.js' }
> Connected to ETCARS
> Game detected: ETS2
> Using Discord Application ID 432559364772200479
> { code: 4000, message: 'No Client ID Specified' }

**Comment by PLASMAchicken** [comment]
How do u give the rpc client the client id?

**Comment by SgtBreadStick** [comment]
it detects 2 different games, ATS or ETS2, it switches to the game. We have the main index.js which goes to RichPresenceManager.js then the config.js which has the IDs,

The config.js shows
>    applications: {
>         ets2: '432559364772200479',
>         ats: '454028920107565107',
>     },

The RichPresenceManager.js shows
>                         if (!instance.rpcReady) {
> 
>                             instance.rpcOnChangingState = true;
> 
>                             // getting application id (default ETS2)
>                             var applicationID = config.applications.ets2;
> 
>                             // checking if playing ATS
>                             if (instance.isAts(data)) {
>                                 applicationID = config.applications.ats;
>                                 instance.logger.info('Game detected: ATS');
>                             } else
>                                 instance.logger.info('Game detected: ETS2');
> 
>                             instance.logger.info(`Using Discord Application ID ${applicationID}`);
> 
>                             // creating a new Discord RPC Client instance
>                             instance.rpc = new DiscordRPC.Client({
>                                 transport: 'ipc'
>                             });
> 
>                             // login to RPC
>                             instance.rpc.login(applicationID).then(() => {
>                                 instance.logger.info('Discord RPC ready');
>                                 // cleaning up variables to save RPC Client state
>                                 instance.rpcReady = true;
>                                 instance.rpcOnChangingState = false;
>                             }).catch(console.error);
>                         }

The version on github is this
https://github.com/VirtualTruckerRPC/Virtual-Trucker-Rich-Presence

**Comment by Lewdcario** [comment]
[Here you go](https://github.com/discordjs/RPC/blob/master/test/rp.js#L46), the correct way to login as per the example.

**Comment by SgtBreadStick** [comment]
I have gone and set it to the correct way to login and when the Discord-RPC destroy function is called it shows this error. It hasn't done this is previous versions either...

> Discord RPC Client destroyed
> MP Checker interval reset
> Location Checker interval reset
> (node:14760) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).destroy is not a function
>     at RPCClient.destroy (C:\Users\supac\Desktop\Things\VT-RPC 2\node_modules\discord-rpc\src\Client.js:639:11)
>     at RichPresenceManager.destroyRPCClient (C:\Users\supac\Desktop\Things\VT-RPC 2\RichPresenceManager.js:324:22)
>     at ETCarsClient.<anonymous> (C:\Users\supac\Desktop\Things\VT-RPC 2\RichPresenceManager.js:139:22)
>     at ETCarsClient.emit (events.js:182:13)
>     at ETCarsClient.receiveError (C:\Users\supac\Desktop\Things\VT-RPC 2\node_modules\etcars-node-client\index.js:181:14)
>     at Socket.etcarsSocket.on (C:\Users\supac\Desktop\Things\VT-RPC 2\node_modules\etcars-node-client\index.js:88:26)
>     at Socket.emit (events.js:182:13)
>     at emitErrorNT (internal/streams/destroy.js:82:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:14760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:14760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Discord RPC Client destroyed
> (node:14760) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).destroy is not a function
>     at RPCClient.destroy (C:\Users\supac\Desktop\Things\VT-RPC 2\node_modules\discord-rpc\src\Client.js:639:11)
>     at RichPresenceManager.destroyRPCClient (C:\Users\supac\Desktop\Things\VT-RPC 2\RichPresenceManager.js:324:22)
>     at ETCarsClient.<anonymous> (C:\Users\supac\Desktop\Things\VT-RPC 2\RichPresenceManager.js:139:22)
>     at ETCarsClient.emit (events.js:182:13)
>     at ETCarsClient.receiveError (C:\Users\supac\Desktop\Things\VT-RPC 2\node_modules\etcars-node-client\index.js:181:14)
>     at Socket.etcarsSocket.on (C:\Users\supac\Desktop\Things\VT-RPC 2\node_modules\etcars-node-client\index.js:88:26)
>     at Socket.emit (events.js:182:13)
>     at emitErrorNT (internal/streams/destroy.js:82:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> (node:14760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by devsnek** [comment]
@SgtBreadStick can you verify what version of rpc you're using

**Comment by SgtBreadStick** [comment]
npm discord-rpc@3.0.0

**Comment by KeysHD** [comment]
I dont know soo much about RPC.
But i think you need to use this:
`rpc.login({ clientId: ClientId });`

**Comment by SgtBreadStick** [comment]
After many attempts it still shows the same error, i will keep the rpc downgraded to the previous version that worked, i tried literally everything and still same error everytime

**Comment by devsnek** [comment]
@SgtBreadStick i think your `RichPresenceManager.destroyRPCClient` has some bugs

**Comment by SgtBreadStick** [comment]
i'll try that, see how it goes, thanks. I dont understand why it does this because it was fine before
