### ISSUE TITLE
Add Activity Types

### ISSUE THREAD

**Issue by adlerluiz** [discordjs/RPC#48]
Add Activity Types according to discord docs

https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-types
![image](https://user-images.githubusercontent.com/2112638/47259267-64168c80-d47d-11e8-977d-cae31f7bfe66.png)

**Comment by SirBearnee** [comment]
Are you talking about [this](https://discord.js.org/#/docs/main/stable/class/Presence)?

**Comment by iCrawl** [comment]
You linked the gateway, thats not relevant to RPC. RPC does not yet have activity types

https://github.com/discordapp/discord-rpc/issues/71
