### ISSUE TITLE
Incorrect OAuth token flow

### ISSUE THREAD

**Issue by theGordHoard** [discordjs/RPC#53]
It seems as if the token flow query parameters are incorrect in the `authorize()` function. Currently it looks like this:
```javascript
const response = await this.fetch('POST', '/oauth2/token', {
  data: new URLSearchParams({
    client_id: this.clientId,
    code,
    grant_type: 'authorization_code',
    redirect_uri: redirectUri,
  }),
});
```
It seems to be missing the `client_secret` and `scope`, as is required for the OAuth token flow. I can open a PR if wanted.

**Comment by devsnek** [comment]
client_secret isn't used on `/oauth2/token`, since you already have `code` at that point.
