### ISSUE TITLE
Cannot connect to RPC

### ISSUE THREAD

**Issue by Ayfri** [discordjs/RPC#63]
I use an extension into VSCode to modify my Rich Presence but when I start VSCode, it says "Cannot connect to Discord RPC : write EPIPE" :/

I'm on Discord PTB and I have VSCode 1.33.0.

**Comment by devsnek** [comment]
which vscode extension are you using? this repo isn't actually for any vs code extensions but if it's the one by icrawl I might be able to help a little bit

**Comment by Ayfri** [comment]
It's that one !

**Comment by Ayfri** [comment]
> 
> 
> which vscode extension are you using? this repo isn't actually for any vs code extensions but if it's the one by icrawl I might be able to help a little bit
