### ISSUE TITLE
sendJoinRequest callback?

### ISSUE THREAD

**Issue by BopItFreak** [discordjs/RPC#64]
I honestly have no idea how the "Ask to Join" feature works. It seems so simple with the C++ lib, but i don't know c++ so I can't use it. I'm assuming every time someone clicks the "join" button on my profile, some callback is supposed to fire. I can't figure out how all this works, and some examples would be very much appreciated. No one seems to know anything about this on the official discordjs discord server. Thanks.

**Comment by JustYanns** [comment]
I cannot answer this question but I noticed something weird, the `sendJoinRequest` method "calls" `RPCCommand.SEND_ACTIVITY_JOIN_REQUEST` which doesn't exist in `constants.js` since the last update of this file ...
