### ISSUE TITLE
RPC Connection Timeout

### ISSUE THREAD

**Issue by SandwichDev** [discordjs/RPC#70]
I've been recently getting this RPC_CONNECTION_TIMEOUT for no apparent reason. It was working but then suddenly stopped and I kept on getting this error.
![image](https://user-images.githubusercontent.com/36942104/65359344-39234400-dbca-11e9-9f9c-658cead589f0.png)

**Comment by SandwichDev** [comment]
Apparently restarting discord solves this.

**Comment by Hailyyy** [comment]
e

**Comment by mustafa-archived** [comment]
e

**Comment by peywan** [comment]
didnt solve it for me sandwichDev
