### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by LittleEndu** [discordjs/RPC#73]
Currently installing discord-rpc in npm results in this tree:
```
+-- discord-rpc@3.1.0
| +-- node-fetch@2.6.0
| `-- ws@7.1.2
|   `-- async-limiter@1.0.1
`-- UNMET PEER DEPENDENCY register-scheme@github:devsnek/node-register-scheme
```

I'm having issues with the lib and am not sure if this might be the cause

**Comment by devsnek** [comment]
that's not an error. register-scheme allows you to register the game to discord if you plan to let discord launch it. it isn't normally needed.
