### ISSUE TITLE
WebSocket transport doesn't work when IPC does

### ISSUE THREAD

**Issue by Malkierian** [discordjs/RPC#78]
So far as I can tell, the WebSocket simply fails to open the connection, but IPC succeeds with the exact same setup and information (just switching the `transport` value when creating Discord.Client). I need the WS version to work because I need to use this through Browserify (but this is still failing when running through Node before Browserify). I don't know what to debug myself, but if you could give me a direction to go in, I can get you whatever information you need. I have debugged `websocket.js` a bit, and found that `ws` has a ready state of 3 immediately after it tries instantiating it, so the connection is just silently failing for whatever reason.

**Comment by Malkierian** [comment]
Oh, and `rpc.login`'s catch is simply outputting "undefined".

**Comment by devsnek** [comment]
WebSocket requires being whitelisted by discord.

**Comment by Malkierian** [comment]
By that, I assume you mean that list that has a limit of 50 people that you set in the developer portal? Well that's no good. Is there a way, then, to make IPC work in browser environments like Chromium (where the `net` module isn't avaiable)?

**Comment by devsnek** [comment]
That's not what I mean. WebSocket transport is not available without explicitly being given access.

**Comment by Malkierian** [comment]
Ah, well I need to prove that this can work before anyone can go to Discord for approval. Anything on my question about IPC without `net`?

**Comment by devsnek** [comment]
there is no such functionality.
