### ISSUE TITLE
Discord RPC not changing activity or freezes (client not destroying or clearing, even after closing client)

### ISSUE THREAD

**Issue by SgtBreadStick** [discordjs/RPC#80]
Recently a discord update was published (or it seems like it) and ever since the discordjs/RPC npm package has been having many issues. One of them being that discord's rpc activity does not change and will just be frozen until discord is restarted (even after node client is closed).

Example:
<img src="https://i.sgtbrdstk.xyz/v5wgay.png">
Code used: [https://github.com/VirtualTruckerRPC/Virtual-Trucker-Rich-Presence/tree/dev](url)

Is this a known issue? As it seems to be quite a major bug.

**Comment by devsnek** [comment]
I can't reproduce this problem.

**Comment by SgtBreadStick** [comment]
Strange, it's very random when it happens. Sometimes it will be perfectly fine and sometimes it does the above. I'll see if i can find a way to reproduce (as right now its just chance)

**Comment by Timeraa** [comment]
Can't reproduce either.

**Comment by SwurvZ** [comment]
I am also having this exact same issue 
<img src="https://legendaryscar.xyz/ss/xm3o40.png">

**Comment by devsnek** [comment]
It seems to me it is a problem in your virtual trucker code, not this library.

**Comment by SgtBreadStick** [comment]
I've been figuring out what has been causing the issues.
This error has been spit out when the game closed and RPC client tried destroying.

[https://pastebin.com/0WVzXunM](url)
