### ISSUE TITLE
Set priority against other apps that user RPC

### ISSUE THREAD

**Issue by Pickysaurus** [discordjs/RPC#84]
Hey,

This is more a feature request, but I'd like to be able to set my RPC state as low priority so if you open a "proper" game it'll remove my status and use the one from the game. Is such a thing possible?

**Comment by devsnek** [comment]
You'd have to ask discord to provide this functionality first, and then I could integrate it into this library.

**Comment by Pickysaurus** [comment]
Thanks for the fast reply!
